CREATE TABLE users (user_id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50),email VARCHAR(100) UNIQUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE orders (order_id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE);

CREATE TABLE user_logs (log_id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,action VARCHAR(100),log_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO users (name, email) VALUES ('Jane', 'jane@example.com');
INSERT INTO orders (user_id) VALUES (LAST_INSERT_ID());